'''

import mysql.connector as mysql
from mysql.connector import Error
import pandas as pd

db = mysql.connect(
    host = "localhost",
    user = "root ",
   passwd = "Giuliagiulia3"
)
print(db)
'''

